# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: portalAdmin
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDcyZDBiYjc2YWFkMjA2NmI3MzY5MDA2MTFkOTYyZTJmODNmYzE1YTU1NGM3YjMyMTE3NmRmMjQwNTAxNjE5NTdlY2RjY2Q2NjQ1OWYxYmRiNGM0NmVkZjhkMzI1M2ExN2EzNzk3YmI1NWI5NTAzYzE5OTU2MWRhNDkxMzMwZGM=
