# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: portaladmin
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  evolution:
    extends:
      file: ./evolution.yml
      service: evolution
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  evolution_instances:
